# Generated by Django 4.1.3 on 2023-02-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
